# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56206370242de31227b3569ad7d0e376fd425a6fc7b19ebc1763fb78ea3457fba4ba0ff05cd44bcc5cc62c6e348de8f01f29fef4b89b8cb23337afa98255f72b

test:
  secret_key_base: 7fa3a4440c17a1b64bea9df8be511a8aad81ff189f7a655b4193da36ce2d0a625c5da6b939969643c918b7b761a5c006cd23bf7b17aa1bada579d1ce7650a0b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
